config/routes.rb
Rails.application.routes.draw do



  get "/signup" => "users#new"
  get "/users" => "users#index"
  post "/users" => "users#create"

  get "/account" => "users#edit"
  patch "/account" => "users#update"


  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/pictures' => 'pictures#index'
  post "/upload" => "pictures#new"



  resources :users, :pictures
  resources :pics
  root to: 'pics#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord
	has_attached_file :image
	validates_attachment :image,
		content_type: { content_type: /\Aimage\/.*\z/ },
		size: { less_than: 1.megabyte }

end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user

  has_attached_file :image

end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures

  has_secure_password
  validates :first_name, :last_name, :email, presence: true
  # has_attached_file :avatar
  # Validate content type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end




end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: [:show, :download]
 
  def index
    @pics = Pic.order('created_at DESC')
  end
 
  def new
    @pic = Pic.new
  end
 
  def show
  end
 
  def create
    @pic = Pic.new(pic_params)
    if @pic.save
      redirect_to pics_path
    else
      render :new
    end
  end
 
  private
 
  def pic_params
    params.require(:pic).permit(:title, :description, :image)
  end
 
  def set_pic
    @pic = Pic.find(params[:id])
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  # before_filter :authorize
  # GET /pictures
  # GET /pictures.json

  def index
    @picture = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  # def update
  #   respond_to do |format|
  #     if @picture.update(picture_params)
  #       format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @picture }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @picture.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  # def destroy
  #   @picture.destroy
  #   respond_to do |format|
  #     format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # before_filter :authorize



  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/pictures'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  
  def index
    User.all
  end

  def new
  end

  def show
    @user = current_user
  end

  def create
      user = User.new(user_params)
      if user.save
        session[:user_id] = user.id
        redirect_to '/'
      else
        redirect_to '/signup'
      end
  end

  def user_params
    params.require(:user).permit(:first_name,:last_name, :email, :password, :password_confirmation)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
  if @user.update!(user_params)
    redirect_to pictures_path
  else
    redirect_to account_path
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photogur</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content= "width=devide=width, initial-scale=1.0">
  </head>

  <body>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- You can update your application layout file to show the user's name if they're logged in and some contextual links. -->
    <% if current_user %>
    Signed in as <%= current_user.first_name %> | <%= link_to "Logout", '/logout' %><br>
    <%= link_to 'Upload Picture', 'pictures' %>
    <%= link_to 'Account', account_path %>
    <% else %>
    <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>



    <%= yield %>
  </div>
  </body>
</html>

app/views/pics/_form.html.erb
<%= form_for pic do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
 
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
 
  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
 
  <%= f.submit %>
<% end %>

app/views/pics/_pic.html.erb
<li>
  <strong><%= image_tag pic.image.url, size: '250'%><%= link_to pic.title, pic_path(pic) %></strong>
</li>

app/views/pics/index.html.erb
<h1>CapSoul</h1>
 
<%= link_to 'Add Pic', new_pic_path %>
<ul>
  <%= render @pics %>
</ul>

app/views/pics/new.html.erb
<h1>Add Pic</h1>
 
<%= render 'form', pic: @pic %>

app/views/pics/show.html.erb
<h1><%= @pic.title %> by <%= @pic.author %></h1>
 
<%= image_tag(@pic.image.url) if @pic.image.exists? %>
 
<p><%= @pic.description %></p>

app/views/pictures/form.html.erb
<%= form_for book do |f| %>

<div>
   <%= f.label :image %>
   <%= f.file_field :image %>
 </div>

 <div>
   <%= f.label :description %>
   <%= f.text_area :description %>
 </div>

 <%= f.submit %>
<% end %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>CapSOUL</h1>

<% link_to 'Add Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<!-- <%= link_to 'Back', pictures_path %> -->

app/views/settings/edit.html.erb
<h1>Hey</h1>

<p> <% @user %> </p>

app/views/users/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photogur</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content= "width=devide=width, initial-scale=1.0">
  </head>

  <body>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- You can update your application layout file to show the user's name if they're logged in and some contextual links. -->
    <% if current_user %>
    Signed in as <%= current_user.first_name %> | <%= link_to "Logout", '/logout' %><br>
    <%= link_to 'Upload Picture', 'pictures' %>
    <%= link_to 'Account', account_path %>
    <% else %>
    <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>



    <%= yield %>
  </div>
  </body>
</html>

app/views/users/edit.html.erb
<br>
<h1> Update Your Profile </h1>

<%= form_for @user do |f| %>
  <p>
  <%= f.label :first_name %><br>
  <%= f.text_area :first_name %>
  </p>

  <p>
  <%= f.label :last_name %><br>
  <%= f.text_area :last_name %>
  </p>
  <p>
  <%= f.label :email %><br>
  <%= f.text_area :email %>
  </p>
  <p>
  <%= f.submit %>
  </p>
  <% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<% User.all.each do |person| %>
  <%= person.first_name %>
   <%= link_to "Show", person %><br>
<% end %>

<!-- <% User.all.each do |person| %>
  <%= person.first_name %>
   <%= link_to "Show", person %><br>
<% end %> -->

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  First Name: <%= f.text_field :first_name %> <br>
  Last Name: <%= f.text_field :last_name %> <br>
  Avatar: <%= f.file_field :avatar %> <br>
  Email: <%= f.text_field :email %> <br>
  Password: <%= f.password_field :password %> <br>
  Password Confirmation: <%= f.password_field :password_confirmation %>

  <%= f.submit "Submit" %>



<% end %>